### ISSUE TITLE
[BUG] Catch Data

### ISSUE THREAD

**Issue by gambhirsharma** [Dharmik48/notes-react-firebase-v2.0#12]
### Description

When you log in to the website and reload it. It logs out without saving the login info. And you have to log in again which is very bad for UX.

# Solution
- Save the login info in form of catch data.

### Screenshots

https://user-images.githubusercontent.com/69895353/184541023-7dca68f0-5428-4d3f-84dd-dc05792cc6df.mp4

**Comment by Dharmik48** [comment]
Agreed, the need to log in every time the user refreshes is a bad experience.

We need to fix this fast!

**Comment by dangvu0502** [comment]
I would love to contribute to this issue. Can you assign this for me ?

**Comment by Dharmik48** [comment]
Sure! I have assigned you @dangvu0502 🚀

**Comment by Dharmik48** [comment]
Closed with #17
