### ISSUE TITLE
What to add for config?

### ISSUE THREAD

**Issue by ArshErgon** [Dharmik48/notes-react-firebase-v2.0#8]
### What would you like to share?

```
Compiled with problems:X

ERROR in ./src/firebase/firebase.js 6:0-40

Module not found: Error: Can't resolve '../firebase/config' in '/home/USER/openSource/notes-react-firebase-v2.0/src/firebase'
```
I'm having this error because inside `firebase` its calling a file `config` and its not present, do I have to create a firebase account for the config?

**Comment by SalmanShahid888** [comment]
> I'm having this error because inside firebase its calling a file config and its not present, do I have to create a firebase account for the config?

Make Sure to read the README.md on how to setup this project.  I have Updated it with steps to view this project. Let me know if you run into a problem 👽

**Comment by ArshErgon** [comment]
@SalmanShahid888 yeah I saw your pull request, I have done everything install firebase and copied the config file, but there's nothing in the website, not a single error on terminal, I think I'm severing files wrongly, can you guide me on this?
file: `index.js`
```
import React from 'react'
import ReactDOM from 'react-dom'
import App from './components/App'
import Account from './components/Account'
import CreateNote from './components/CreateNote'
import Notes from './components/Notes'
import SearchBar from './components/SearchBar'
import SideBar from './components/SideBar'
import './css/index.css'

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
    <Account />
    <CreateNote />
    <Notes />
    <SearchBar />
    <SideBar />
  </React.StrictMode>
);

```

**Comment by SalmanShahid888** [comment]
>  but there's nothing in the website, not a single error on terminal

You need to sign in before you make any notes. Let me know if it works after signing in. Click on the sign in button on the top right. it should sign you in with you google account.

**Comment by ArshErgon** [comment]
@SalmanShahid888 I'm already signIn thats how I get the API key, the above problem I solved, his components isn't visible
error on console:
```
a: null
code: "auth/invalid-api-key"
message: "Your API key is invalid, please check you have copied it correctly."
[[Prototype]]: Error
```
Edit:
I even deleted the firebase app and started a new one, still the same error

**Comment by SalmanShahid888** [comment]
@ArshErgon Can you make a branch of your project so I can take a look?

**Comment by Dharmik48** [comment]
Hey @ArshErgon, I have the config file for the main firebase app so you will be able to run the project without any errors.

Just make sure you pull the changes before running😊

**Comment by Dharmik48** [comment]
And thanks a lot @SalmanShahid888 for helping @ArshErgon out to solve his error😊
